/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ucloudlink.css.avro.avsc;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** 用户信息 */
@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4401567455959931516L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.ucloudlink.css.avro.avsc\",\"doc\":\"用户信息\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"主键ID\",\"default\":\"0\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"名字\"},{\"name\":\"age\",\"type\":[\"int\",\"null\"],\"doc\":\"年龄\",\"default\":\"1\"},{\"name\":\"list\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"null\"],\"doc\":\"年龄\",\"default\":\"1\"},{\"name\":\"map\",\"type\":[{\"type\":\"map\",\"values\":\"long\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"年龄\",\"default\":\"1\"},{\"name\":\"fmd\",\"type\":[{\"type\":\"fixed\",\"name\":\"md5\",\"size\":16},\"null\"],\"doc\":\"年龄\",\"default\":\"1\"},{\"name\":\"email\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"邮箱\"}],\"aliases\":[\"User1\",\"User2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<User> ENCODER =
      new BinaryMessageEncoder<User>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<User> DECODER =
      new BinaryMessageDecoder<User>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<User> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<User> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<User>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this User to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a User from a ByteBuffer. */
  public static User fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** 主键ID */
  @Deprecated public long id;
  /** 名字 */
  @Deprecated public java.lang.String name;
  /** 年龄 */
  @Deprecated public java.lang.Integer age;
  /** 年龄 */
  @Deprecated public java.util.List<java.lang.String> list;
  /** 年龄 */
  @Deprecated public java.util.Map<java.lang.String,java.lang.Long> map;
  /** 年龄 */
  @Deprecated public com.ucloudlink.css.avro.avsc.md5 fmd;
  /** 邮箱 */
  @Deprecated public java.lang.String email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User() {}

  /**
   * All-args constructor.
   * @param id 主键ID
   * @param name 名字
   * @param age 年龄
   * @param list 年龄
   * @param map 年龄
   * @param fmd 年龄
   * @param email 邮箱
   */
  public User(java.lang.Long id, java.lang.String name, java.lang.Integer age, java.util.List<java.lang.String> list, java.util.Map<java.lang.String,java.lang.Long> map, com.ucloudlink.css.avro.avsc.md5 fmd, java.lang.String email) {
    this.id = id;
    this.name = name;
    this.age = age;
    this.list = list;
    this.map = map;
    this.fmd = fmd;
    this.email = email;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return age;
    case 3: return list;
    case 4: return map;
    case 5: return fmd;
    case 6: return email;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.String)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: list = (java.util.List<java.lang.String>)value$; break;
    case 4: map = (java.util.Map<java.lang.String,java.lang.Long>)value$; break;
    case 5: fmd = (com.ucloudlink.css.avro.avsc.md5)value$; break;
    case 6: email = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return 主键ID
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * 主键ID
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return 名字
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * 名字
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return 年龄
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * 年龄
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'list' field.
   * @return 年龄
   */
  public java.util.List<java.lang.String> getList() {
    return list;
  }

  /**
   * Sets the value of the 'list' field.
   * 年龄
   * @param value the value to set.
   */
  public void setList(java.util.List<java.lang.String> value) {
    this.list = value;
  }

  /**
   * Gets the value of the 'map' field.
   * @return 年龄
   */
  public java.util.Map<java.lang.String,java.lang.Long> getMap() {
    return map;
  }

  /**
   * Sets the value of the 'map' field.
   * 年龄
   * @param value the value to set.
   */
  public void setMap(java.util.Map<java.lang.String,java.lang.Long> value) {
    this.map = value;
  }

  /**
   * Gets the value of the 'fmd' field.
   * @return 年龄
   */
  public com.ucloudlink.css.avro.avsc.md5 getFmd() {
    return fmd;
  }

  /**
   * Sets the value of the 'fmd' field.
   * 年龄
   * @param value the value to set.
   */
  public void setFmd(com.ucloudlink.css.avro.avsc.md5 value) {
    this.fmd = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return 邮箱
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * 邮箱
   * @param value the value to set.
   */
  public void setEmail(java.lang.String value) {
    this.email = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static com.ucloudlink.css.avro.avsc.User.Builder newBuilder() {
    return new com.ucloudlink.css.avro.avsc.User.Builder();
  }

  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static com.ucloudlink.css.avro.avsc.User.Builder newBuilder(com.ucloudlink.css.avro.avsc.User.Builder other) {
    return new com.ucloudlink.css.avro.avsc.User.Builder(other);
  }

  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static com.ucloudlink.css.avro.avsc.User.Builder newBuilder(com.ucloudlink.css.avro.avsc.User other) {
    return new com.ucloudlink.css.avro.avsc.User.Builder(other);
  }

  /**
   * RecordBuilder for User instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    /** 主键ID */
    private long id;
    /** 名字 */
    private java.lang.String name;
    /** 年龄 */
    private java.lang.Integer age;
    /** 年龄 */
    private java.util.List<java.lang.String> list;
    /** 年龄 */
    private java.util.Map<java.lang.String,java.lang.Long> map;
    /** 年龄 */
    private com.ucloudlink.css.avro.avsc.md5 fmd;
    /** 邮箱 */
    private java.lang.String email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ucloudlink.css.avro.avsc.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.list)) {
        this.list = data().deepCopy(fields()[3].schema(), other.list);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.map)) {
        this.map = data().deepCopy(fields()[4].schema(), other.map);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fmd)) {
        this.fmd = data().deepCopy(fields()[5].schema(), other.fmd);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.email)) {
        this.email = data().deepCopy(fields()[6].schema(), other.email);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ucloudlink.css.avro.avsc.User other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.list)) {
        this.list = data().deepCopy(fields()[3].schema(), other.list);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.map)) {
        this.map = data().deepCopy(fields()[4].schema(), other.map);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fmd)) {
        this.fmd = data().deepCopy(fields()[5].schema(), other.fmd);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.email)) {
        this.email = data().deepCopy(fields()[6].schema(), other.email);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * 主键ID
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * 主键ID
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * 主键ID
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * 主键ID
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * 名字
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * 名字
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * 名字
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * 名字
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * 年龄
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * 年龄
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setAge(java.lang.Integer value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * 年龄
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * 年龄
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearAge() {
      age = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'list' field.
      * 年龄
      * @return The value.
      */
    public java.util.List<java.lang.String> getList() {
      return list;
    }

    /**
      * Sets the value of the 'list' field.
      * 年龄
      * @param value The value of 'list'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setList(java.util.List<java.lang.String> value) {
      validate(fields()[3], value);
      this.list = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'list' field has been set.
      * 年龄
      * @return True if the 'list' field has been set, false otherwise.
      */
    public boolean hasList() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'list' field.
      * 年龄
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearList() {
      list = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'map' field.
      * 年龄
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Long> getMap() {
      return map;
    }

    /**
      * Sets the value of the 'map' field.
      * 年龄
      * @param value The value of 'map'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setMap(java.util.Map<java.lang.String,java.lang.Long> value) {
      validate(fields()[4], value);
      this.map = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'map' field has been set.
      * 年龄
      * @return True if the 'map' field has been set, false otherwise.
      */
    public boolean hasMap() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'map' field.
      * 年龄
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearMap() {
      map = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'fmd' field.
      * 年龄
      * @return The value.
      */
    public com.ucloudlink.css.avro.avsc.md5 getFmd() {
      return fmd;
    }

    /**
      * Sets the value of the 'fmd' field.
      * 年龄
      * @param value The value of 'fmd'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setFmd(com.ucloudlink.css.avro.avsc.md5 value) {
      validate(fields()[5], value);
      this.fmd = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'fmd' field has been set.
      * 年龄
      * @return True if the 'fmd' field has been set, false otherwise.
      */
    public boolean hasFmd() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'fmd' field.
      * 年龄
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearFmd() {
      fmd = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * 邮箱
      * @return The value.
      */
    public java.lang.String getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * 邮箱
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder setEmail(java.lang.String value) {
      validate(fields()[6], value);
      this.email = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * 邮箱
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'email' field.
      * 邮箱
      * @return This builder.
      */
    public com.ucloudlink.css.avro.avsc.User.Builder clearEmail() {
      email = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public User build() {
      try {
        User record = new User();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.list = fieldSetFlags()[3] ? this.list : (java.util.List<java.lang.String>) defaultValue(fields()[3]);
        record.map = fieldSetFlags()[4] ? this.map : (java.util.Map<java.lang.String,java.lang.Long>) defaultValue(fields()[4]);
        record.fmd = fieldSetFlags()[5] ? this.fmd : (com.ucloudlink.css.avro.avsc.md5) defaultValue(fields()[5]);
        record.email = fieldSetFlags()[6] ? this.email : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<User>
    WRITER$ = (org.apache.avro.io.DatumWriter<User>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<User>
    READER$ = (org.apache.avro.io.DatumReader<User>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
