/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ucloudlink.css.avro.ipc;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum HandshakeMatch {
  BOTH, CLIENT, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HandshakeMatch\",\"namespace\":\"com.ucloudlink.css.avro.ipc\",\"symbols\":[\"BOTH\",\"CLIENT\",\"NONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
