/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ucloudlink.css.avro.avpr;

@SuppressWarnings("all")
/** user api */
@org.apache.avro.specific.AvroGenerated
public interface IUserDao {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"IUserDao\",\"namespace\":\"com.ucloudlink.css.avro.avpr\",\"doc\":\"user api\",\"types\":[{\"type\":\"record\",\"name\":\"Group\",\"doc\":\"组信息\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"主键ID\",\"default\":\"0\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"名字\"},{\"name\":\"groupId\",\"type\":[\"int\",\"null\"],\"doc\":\"groupId\",\"default\":\"1\"}],\"aliases\":[\"Group1\",\"Group2\"]},{\"type\":\"record\",\"name\":\"Organize\",\"doc\":\"组信息\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"主键ID\",\"default\":\"0\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"名字\"},{\"name\":\"group\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Fad\",\"size\":16}],\"doc\":\"groupId\"}],\"aliases\":[\"Organize1\",\"Organize2\"]},{\"type\":\"record\",\"name\":\"Role\",\"doc\":\"角色信息\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"主键ID\",\"default\":\"0\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"名字\"},{\"name\":\"roleId\",\"type\":[\"int\",\"null\"],\"doc\":\"roleId\",\"default\":\"1\"}],\"aliases\":[\"Role1\",\"Role2\"]}],\"messages\":{\"test1\":{\"doc\":\"Say hello.\",\"request\":[{\"name\":\"id\",\"type\":\"int\"}],\"response\":\"Role\"},\"test2\":{\"doc\":\"test2.\",\"request\":[{\"name\":\"group\",\"type\":\"Group\"}],\"response\":\"null\"}}}");
  /**
   * Say hello.
   */
  com.ucloudlink.css.avro.avpr.Role test1(int id) throws org.apache.avro.AvroRemoteException;
  /**
   * test2.
   */
  java.lang.Void test2(com.ucloudlink.css.avro.avpr.Group group) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** user api */
  public interface Callback extends IUserDao {
    public static final org.apache.avro.Protocol PROTOCOL = com.ucloudlink.css.avro.avpr.IUserDao.PROTOCOL;
    /**
     * Say hello.
     * @throws java.io.IOException The async call could not be completed.
     */
    void test1(int id, org.apache.avro.ipc.Callback<com.ucloudlink.css.avro.avpr.Role> callback) throws java.io.IOException;
    /**
     * test2.
     * @throws java.io.IOException The async call could not be completed.
     */
    void test2(com.ucloudlink.css.avro.avpr.Group group, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}